name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 7.0.1
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  dart_countries: ^3.0.2
  diacritic: ^0.1.3
  # flag: ^6.0.0
  flag:
    git:
      url: https://github.com/LunaGao/flag_flutter.git
      ref: 988b830bca32a7552e4f75a5795e16f7cecf2958
  intl: ^0.17.0
  phone_numbers_parser: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
